### ISSUE TITLE
Tutorial access to the raw radar data cube

### ISSUE THREAD

**Issue by ArthurOuaknine** [ZendarInc/ZendarSDK#25]
Hello.

I would like to explore the raw radar data cubes you have released in your dataset but I have a few difficulties to use your DSK with the protobuf format. As far as I understand the structure of your dataset, the raw radar data cubes are stored in the 'range-Doppler' folder in both 'left_rd.pbs' and 'right_rd.pbs' files.

Consider that the required settings have been realised following your instructions (cmake, python environment...).
Let's define an example using the sequence '2020-02-03_2252/001' to read the raw radar data from the left radar.
I'm trying to read the data with the ProtoStreamReader() class, I'm using the following parameters:
 - `data_stream_path = '../2020-02-03_2252/001/range_Doppler/left_rd.pbs'`
 - `proto_type = RangeDopplerFrame`
 - `python_type = RadarImage`
Where `RangeDopplerFrame` is from the generated data_pb2 file after building the environment and `RadarImage()` the class from the radar_image.py script.

I tried to run a simple script to  iterate on the reader:
```python
data = ProtoStreamReader(path_data, RangeDopplerFrame, RadarImage)  
data.__enter__()  
data = iter(data)  
radar_image = next(data)
```
I obtained an error in the line 30 of radar_image.py, `AttributeError: frame_id`. It seems that `RadarImage` should be instanciated beforehand.

It is not clear in your repo how we can have access to the raw radar data cube. Is there a simpler way than using ProtoStreamReader() to read the data? Is this the correct way to use the ProtoStreamReader()?
Could you please provide a very simple script example to access a frame of raw radar data cube (as a numpy array)? 

Thank you very much for your help.
Best.
Arthur

**Comment by plb9772** [comment]
Hi,

Most of the steps you have taken to read the range-doppler cube are good. Your issue is that you use `python_type = RadarImage` in your `ProtoStreamReader` which is not working because `RadarImage` is the python class corresponding to the SAR Images (which you can find under `.../2020-02-03_2252/001/SAR_with_detection_points/1739000J1Q_images.pbs` for example) and not to the range-doppler.

Therefore, you have to create your own python class for the range-doppler. An example would be:
```python
from data_pb2 import RangeDopplerFrame
from radar_data_streamer import RadarData

class RangeDoppler(RadarData):
    """
    This class is a Python representation of the protobuf Image object for
    convinent downstream operations
    """
    def __init__(self, timestamp, data):
        self.timestamp = timestamp
        self.data = data

    @classmethod
    def from_proto(cls, range_doppler_pb):
        timestamp = range_doppler_pb.timestamp
        data = np.frombuffer(range_doppler_pb.data, dtype=np.complex64)

        return cls(timestamp, data)

    def to_proto(self, timestamp, range_doppler):
        range_doppler_pb = RangeDopplerFrame()

        range_doppler_pb.timestamp = timestamp
        range_doppler_pb.data = np.ndarray.tobytes(range_doppler)

        return range_doppler_pb
```

Then you can read the protobuf with this code:
```python
data = ProtoStreamReader(path_data, RangeDopplerFrame, RangeDoppler)  
data.__enter__()  
data = iter(data)  
range_doppler = next(data)
```

With this script `range_doppler.data` will be a flat array. You will have to reshape it, according to the information given in `left_rd.pt` (protobuf message `RangeDopplerImageModel`), in your case, you have to reshape it to `(range_axis_params.count, doppler_axis_params.count, num_rx) = (512, 256, 4)`.

In general, I would advice you to look at `/protocol/data.proto` to understand better our protobuf formats, since it includes some documentation for most of the messages.

In order to visualize the range-doppler in a human-readable way, here is a small script you can use:
```python
import matplotlib.pyplot as plt

rd = np.abs(np.mean(range_doppler.data.reshape((512,256,4)), axis = 2))
threshold = np.quantile(rd, 0.999)
rd[rd > threshold] = threshold
rd = np.log10(rd)
rd -= np.median(rd)
rd[rd < 0] = 0
rd = rd / rd.max()

plt.figure()
plt.imshow(np.flipud(rd))
```

I hope this can help, we have plan to update this in the documentation of the repo, but we cannot promise when,
Best,
Pierre-Louis

**Comment by ArthurOuaknine** [comment]
Thanks for your example, it works perfectly well!

**Comment by Jacky-gsq** [comment]
Hi，

I have tried the above way to read radar-doppler data, but I obtain the error of "cannot import name 'RangeDopplerFrame' from 'data_pb2' (/usr/lib/zendar/data_pab2.py".  

Could you help me please? Appreciate it !!!

**Comment by Jacky-gsq** [comment]
Hi，

I have tried the above way to read radar-doppler data, but I obtain the error of "cannot import name 'RangeDopplerFrame' from 'data_pb2' (/usr/lib/zendar/data_pab2.py".  

Could you help me please? Appreciate it !!!

**Comment by Jacky-gsq** [comment]
@ArthurOuaknine @plb9772 
Hi，

I have tried the above way to read radar-doppler data, but I obtain the error of "cannot import name 'RangeDopplerFrame' from 'data_pb2' (/usr/lib/zendar/data_pab2.py".

Could you help me please? Appreciate it !!!

**Comment by ArthurOuaknine** [comment]
Hi.
Did you build the environment correctly before running the script?
If you follow the guidelines in ZendarSDK/python/, a file data_pb2.py should be generated containing the RangeDopplerFrame class. Then you just have to modify the import (or move the file to the correct location) to point this file.
Hope it will help.
